image: node:latest

stages:
  - preBuild
  - build
  - deploy

generateSwagger:
  stage: preBuild
  before_script:
    - npm install @openapitools/openapi-generator-cli -g
  script: 
    - ./generateApiClient.sh

build:
  stage: build
  script: 
    - cd gen
    - npm install
    - npm run build
  artifacts:
    paths:
      - './gen/dist'
    expire_in: 1 day

deploy:
  stage: deploy
  script:
    - cd './gen/dist'
    - echo "//${CI_SERVER_HOST}/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}">.npmrc
    - npm publish
  needs:
    - job: build
      artifacts: true
