components:
  schemas:
    ApiError:
      type: object
      properties:
        title:
          type: string
        message:
          type: string
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-ACCESS-TOKEN
  responses:
    UnauthorizedResponse:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
    GenericErrorResponse:
      description: Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ApiError'
  
